In [1]:
import pandas as pd
import numpy as np

In [4]:
tabela_21 = pd.read_csv('pre-process_2017.csv').head(10)

# Arq1 (Amarelo): Ano, Curso, UF, Regiao, Cat_Administrativa, Cat_Org_Academica;
# Arq2 (Verde): Turno, Conclusao_Ensino_Medio, Inicio_Graduacao;
# Arq4 (Azul): Formacao, Plano_de_Ensino, Condicao_Salas, Condicao_Praticas;

In [5]:
def color_21_arq1(s):
    return np.where(s.isin(['Ano', 'Curso', 'UF', 'Regiao', 'Cat_Administrativa', 'Cat_Org_Academica']), "background-color: yellow;", "")
def color_21_arq2(s):
    return np.where(s.isin(['Turno', 'Conclusao_Ensino_Medio', 'Inicio_Graduacao']), "background-color: chartreuse;", "")
def color_21_arq4(s):
    return np.where(s.isin(['Formacao', 'Plano_de_Ensino', 'Condicao_Salas', 'Condicao_Praticas']), "background-color: deepskyblue;", "")

In [4]:
tabela_21.style.apply_index(color_21_arq1, axis="columns")

In [6]:
tabela_21.style.apply_index(color_21_arq2, axis="columns")

In [7]:
tabela_21.style.apply_index(color_21_arq4, axis="columns")