In [1]:
import pandas as pd
import numpy as np

In [2]:
df_conceito = pd.read_csv('merge_tabelas_conceitos.csv')

In [3]:
df_conceito_faixa = df_conceito[['Nota_Conceito_Faixa']].copy()

In [4]:
df_conceito_faixa

      Nota_Conceito_Faixa
0                       3
1                       4
2                       4
3                       4
4                       4
...                   ...
5833                    3
5834                    2
5835                    4
5836                    5
5837                    5

[5838 rows x 1 columns]

In [5]:
df_tabela_final = pd.read_csv('tabela_final_analise.csv')

In [6]:
df_tabela_final_treinamento = pd.concat([df_tabela_final, df_conceito_faixa], axis=1)

In [7]:
df_tabela_final_treinamento

,Ano,Numero_Notas_Invalidas,Numero_Faltantes,Numero_Participantes,ADS,BCC,EC,GTI,LCC,RC,...,Não contribui,Não sei responder.4,nulos_Formacao,Muito boa,Boa,Regular,Fraca,Muito fraca,Não sei responder.5,Nota_Conceito_Faixa
0,2021,1,4,36,0,41,0,0,0,0,...,7,2,3,5,12,14,5,1,1,3
1,2021,0,27,85,0,112,0,0,0,0,...,15,3,11,25,28,38,5,2,3,4
2,2021,0,17,82,0,99,0,0,0,0,...,4,0,14,28,36,20,1,0,0,4
3,2021,0,12,45,0,57,0,0,0,0,...,1,2,0,19,21,15,2,0,0,4
4,2021,0,4,43,0,47,0,0,0,0,...,1,0,3,21,17,6,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5833,2011,1,2,58,0,61,0,0,0,0,...,0,4,0,14,26,15,2,1,3,3
5834,2011,0,1,5,6,0,0,0,0,0,...,0,1,0,1,3,1,0,0,1,2
5835,2011,0,1,8,9,0,0,0,0,0,...,0,1,0,3,4,0,0,1,1,4
5836,2011,0,0,3,3,0,0,0,0,0,...,0,0,0,0,1,2,0,0,0,5
5837,2011,0,2,35,37,0,0,0,0,0,...,0,0,0,11,17,6,3,0,0,5

In [8]:
df_tabela_final_treinamento.to_csv('./{}.csv'.format('tabela_final_analise_conceito'),index=False)