In [1]:
import pandas as pd
import numpy as np

In [2]:
df_conceito = pd.read_csv('merge_tabelas_conceitos.csv')

In [3]:
df_conceito_faixa = df_conceito[['Nota_Conceito_Faixa']].copy()

In [4]:
df_conceito_faixa

      Nota_Conceito_Faixa
0                       3
1                       4
2                       4
3                       4
4                       4
...                   ...
5833                    3
5834                    2
5835                    4
5836                    5
5837                    5

[5838 rows x 1 columns]

In [5]:
df_tabela_final = pd.read_csv('teste_OHE.csv')

In [6]:
df_tabela_final_treinamento = pd.concat([df_tabela_final, df_conceito_faixa], axis=1)

In [7]:
df_tabela_final_treinamento

,Numero_Notas_Invalidas,Numero_Faltantes,Numero_Participantes,nulos_UF_Ensino_Medio,RO,AC,AM,RR,PA,AP,...,Não contribui,Não sei responder.4,nulos_Formacao,Muito boa,Boa,Regular,Fraca,Muito fraca,Não sei responder.5,Nota_Conceito_Faixa
0,0.024390,0.097561,0.878049,0.073171,0.04878,0.0,0.000000,0.0,0.024390,0.0,...,0.170732,0.048780,0.073171,0.121951,0.292683,0.341463,0.121951,0.024390,0.024390,3
1,0.000000,0.241071,0.758929,0.098214,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.133929,0.026786,0.098214,0.223214,0.250000,0.339286,0.044643,0.017857,0.026786,4
2,0.000000,0.171717,0.828283,0.141414,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.040404,0.000000,0.141414,0.282828,0.363636,0.202020,0.010101,0.000000,0.000000,4
3,0.000000,0.210526,0.789474,0.000000,0.00000,0.0,0.000000,0.0,0.017544,0.0,...,0.017544,0.035088,0.000000,0.333333,0.368421,0.263158,0.035088,0.000000,0.000000,4
4,0.000000,0.085106,0.914894,0.063830,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.021277,0.000000,0.063830,0.446809,0.361702,0.127660,0.000000,0.000000,0.000000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5833,0.016393,0.032787,0.950820,0.049180,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.065574,0.000000,0.229508,0.426230,0.245902,0.032787,0.016393,0.049180,3
5834,0.000000,0.166667,0.833333,0.166667,0.00000,0.0,0.666667,0.0,0.166667,0.0,...,0.000000,0.166667,0.000000,0.166667,0.500000,0.166667,0.000000,0.000000,0.166667,2
5835,0.000000,0.111111,0.888889,0.111111,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.111111,0.000000,0.333333,0.444444,0.000000,0.000000,0.111111,0.111111,4
5836,0.000000,0.000000,1.000000,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.333333,0.666667,0.000000,0.000000,0.000000,5
5837,0.000000,0.054054,0.945946,0.000000,0.00000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.297297,0.459459,0.162162,0.081081,0.000000,0.000000,5

In [8]:
df_tabela_final_treinamento.to_csv('./{}.csv'.format('teste_OHE_treinamento'),index=False)