In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados_21 = pd.read_csv('computacao_enade_2021.csv')

In [42]:
dados_21

,NU_ANO,CO_GRUPO,CO_UF_CURSO,CO_REGIAO_CURSO,CO_CATEGAD,CO_ORGACAD,CO_TURNO_GRADUACAO,NT_GER,ANO_FIM_EM,ANO_IN_GRAD,...,QE_I06,QE_I07,QE_I15,QE_I10,QE_I22,QE_I23,QE_I61,QE_I62,QE_I38,QE_I27
0,2021,BCC,MT,CO,Pública Federal,Universidade,Integral,26.9,2017.0,2018.0,...,B,B,B,A,E,A,6.0,6.0,6.0,6.0
1,2021,BCC,MT,CO,Pública Federal,Universidade,Integral,17.2,2015.0,2016.0,...,D,C,A,D,NaN,C,6.0,5.0,4.0,4.0
2,2021,BCC,MT,CO,Pública Federal,Universidade,Integral,43.9,2014.0,2015.0,...,B,A,A,A,A,C,4.0,4.0,4.0,4.0
3,2021,BCC,MT,CO,Pública Federal,Universidade,Integral,40.7,2014.0,2015.0,...,B,C,A,A,B,D,NaN,NaN,NaN,NaN
4,2021,BCC,MT,CO,Pública Federal,Universidade,Integral,21.7,2017.0,2018.0,...,B,F,A,E,NaN,B,2.0,1.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62026,2021,ADS,PE,NE,Privada SFL,Faculdade,Noturno,18.9,2003.0,2019.0,...,B,A,A,E,E,B,6.0,6.0,1.0,2.0
62027,2021,ADS,PE,NE,Privada SFL,Faculdade,Noturno,20.1,2008.0,2020.0,...,B,C,A,E,C,B,6.0,6.0,6.0,5.0
62028,2021,ADS,PE,NE,Privada SFL,Faculdade,Noturno,18.9,2007.0,2019.0,...,B,D,A,E,C,D,4.0,4.0,3.0,3.0
62029,2021,ADS,PE,NE,Privada SFL,Faculdade,Noturno,27.1,2016.0,2019.0,...,B,E,A,E,B,C,5.0,6.0,4.0,3.0
62030,2021,ADS,SC,SUL,Privada SFL,Faculdade,nan,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dados_21['CO_GRUPO'].dtype # Ver se o formato Object pra string é válido

In [ ]:
dados_21.replace({'CO_GRUPO': {72: 'ADS', 4004: 'BCC', 6409: 'GTI', 4005: 'LCC', 79: 'RC', 4006: 'SI'}}, inplace=True) # inplace=True permite que o df seja modificado diretamente

# dft1 = dft1.astype({"a": np.bool_, "c": np.float64})
dados_21 = dados_21.astype({'CO_GRUPO':str})

In [ ]:
estado_dict = {
11 : 'RO',12 : 'AC', 
13 : 'AM',14 : 'RR',
15 : 'PA',16 : 'AP',
17 : 'TO',21 : 'MA',
22 : 'PI',23 : 'CE',
24 : 'RN',25 : 'PB',
26 : 'PE',27 : 'AL',
28 : 'SE',29 : 'BA',
31 : 'MG',32 : 'ES',
33 : 'RJ',35 : 'SP',
41 : 'PR',42 : 'SC',
43 : 'RS',50 : 'MS',
51 : 'MT',52 : 'GO', 
53 : 'DF'
}

In [ ]:
dados_21['CO_UF_CURSO'].replace(estado_dict,inplace=True)
dados_21 = dados_21.astype({'CO_UF_CURSO':str})

In [ ]:
regiao_dict = {
1 : 'N',2 : 'NE', 
3 : 'SE',4 : 'SUL',
5 : 'CO'
}

In [ ]:
dados_21['CO_REGIAO_CURSO'].replace(regiao_dict,inplace=True)
dados_21 = dados_21.astype({'CO_REGIAO_CURSO':str})

In [ ]:
# Não há IESes do tipo especial

# ies_especial = dados_21[dados_21["CO_CATEGAD"] == 6]
# ies_especial

In [36]:
cat_adm_dict = {
1 : 'Pública Federal',2 : 'Pública Estadual', 
3 : 'Pública Municipal',4 : 'Privada CFL',
5 : 'Privada SFL'
}

In [37]:
dados_21['CO_CATEGAD'].replace(cat_adm_dict,inplace=True)
dados_21 = dados_21.astype({'CO_CATEGAD':str})

In [38]:
# cefet = dados_21[dados_21['CO_ORGACAD'] == 10019]
# cefet

cat_org_dict = {
10019 : 'CEFET',10020 : 'Centro Universitário', 
10022 : 'Faculdade',10026 : 'IFECT',
10028 : 'Universidade'
}

In [39]:
dados_21['CO_ORGACAD'].replace(cat_org_dict,inplace=True)
dados_21 = dados_21.astype({'CO_ORGACAD':str})

In [40]:
turno_dict = {
1 : 'Matutino',2 : 'Vespertino', 
3 : 'Integral',4 : 'Noturno'
}

In [41]:
dados_21['CO_TURNO_GRADUACAO'].replace(turno_dict,inplace=True)
dados_21 = dados_21.astype({'CO_TURNO_GRADUACAO':str})

In [ ]:
# Análise do atributo ANO_FIM_EM

In [ ]:
outliers = dados_21[(dados_21['ANO_FIM_EM'] < 1951) | (dados_21['ANO_FIM_EM'] > 2021)]
outliers

In [ ]:
media = dados_21['ANO_FIM_EM'].mean()
media

In [ ]:
#-------------------------------#